---
abstract: 'Subclass of WebService::Async that has a simple interface to Microsoft Translate Service.'
author:
  - 'keroyon <keroyon@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Async-Microsoft-TranslateV2
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  perl: 5.8.8
resources:
  homepage: http://github.com/keroyonn/p5-WebService-Async-Microsoft-TranslateV2/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/keroyonn/p5-WebService-Async-Microsoft-TranslateV2.git
version: 0.01
